name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and tag Docker image
        run: |
          docker build -t hendrasusanto/go-hello-world-api:latest .
          docker login -u hendrasusanto -p ${{ secrets.DOCKER_PASSWORD }}
          docker push hendrasusanto/go-hello-world-api:latest

      - name: SSH to DigitalOcean droplet and deploy
        uses: appleboy/ghaction-ssh@master
        with:
          host: ${{ secrets.DO_HOST }} # Your droplet's IP address
          username: ${{ secrets.DO_USERNAME }} # Your droplet's username (e.g., root)
          key: ${{ secrets.DO_PRIVATE_KEY }} # Your droplet's private SSH key
          script: |
            docker pull hendrasusanto/go-hello-world-api:latest
            docker stop go-hello-world-container || true
            docker rm go-hello-world-container || true
            docker-compose up -d