name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: hendrasusanto
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t hendrasusanto/go-hello-world-api:latest .
          docker push hendrasusanto/go-hello-world-api:latest

      - name: SSH to DigitalOcean droplet and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_PRIVATE_KEY }}
          script: |
            docker pull hendrasusanto/go-hello-world-api:latest
            docker stop go-hello-world-container || true
            docker rm go-hello-world-container || true
            docker run -d \
              --name go-hello-world-container \
              --restart always \
              -p 8080:8080 \
              hendrasusanto/go-hello-world-api:latest